namespace SundarEmbroidery.Domain;

public enum UserRole { Customer, BusinessUser, Admin }
public enum PriceType { StartingFrom, Fixed, QuoteOnly }
public enum EnquiryStatus { New, Contacted, Quoted, Converted, Closed }
public enum BulkEnquiryStatus { New, Reviewing, Quoted, Accepted, Rejected, ConvertedToOrder }
public enum OrderType { Individual, Bulk }
public enum OrderStatus { Pending, Confirmed, DesignFinalized, InProduction, QualityCheck, ReadyForPickup, ReadyForDispatch, Dispatched, Delivered, Cancelled }

public abstract class Entity { public Guid Id { get; set; } = Guid.NewGuid(); public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class User : Entity { public required string Name { get; set; } public required string MobileNumber { get; set; } public string? Email { get; set; } public required string PasswordHash { get; set; } public UserRole Role { get; set; } }
public sealed class Business : Entity { public Guid OwnerUserId { get; set; } public required string BusinessName { get; set; } public required string Description { get; set; } public required string AddressLine1 { get; set; } public string? AddressLine2 { get; set; } public required string Area { get; set; } public required string City { get; set; } public required string District { get; set; } public required string State { get; set; } public required string Pincode { get; set; } public decimal? Latitude { get; set; } public decimal? Longitude { get; set; } public required string WhatsAppNumber { get; set; } public required string CallingNumber { get; set; } public string? Email { get; set; } public TimeOnly OpeningTime { get; set; } public TimeOnly ClosingTime { get; set; } public string? WeeklyClosingDay { get; set; } public string? GoogleMapsUrl { get; set; } public string? InstagramUrl { get; set; } public string? FacebookUrl { get; set; } public string? LogoUrl { get; set; } public bool IsPanIndiaShipping { get; set; } public bool IsActive { get; set; } = true; }
public sealed class BusinessUser : Entity { public Guid BusinessId { get; set; } public Guid UserId { get; set; } }
public sealed class BusinessServiceArea : Entity { public Guid BusinessId { get; set; } public required string Pincode { get; set; } public required string City { get; set; } public required string State { get; set; } public bool IsActive { get; set; } = true; }
public sealed class Category : Entity { public required string Name { get; set; } public required string Slug { get; set; } public bool IsActive { get; set; } = true; }
public sealed class Product : Entity { public Guid BusinessId { get; set; } public Guid CategoryId { get; set; } public required string Name { get; set; } public required string Slug { get; set; } public required string ShortDescription { get; set; } public required string Description { get; set; } public decimal? StartingPrice { get; set; } public PriceType PriceType { get; set; } public int ProductionDaysMin { get; set; } public int ProductionDaysMax { get; set; } public int MinimumOrderQuantity { get; set; } = 1; public bool IsBulkAvailable { get; set; } public bool IsFeatured { get; set; } public bool IsActive { get; set; } = true; }
public sealed class ProductImage : Entity { public Guid ProductId { get; set; } public required string ImageUrl { get; set; } public int DisplayOrder { get; set; } public bool IsPrimary { get; set; } }
public sealed class Favourite : Entity { public Guid CustomerId { get; set; } public Guid ProductId { get; set; } }
public sealed class Enquiry { public Guid Id { get; set; } = Guid.NewGuid(); public required string CustomerName { get; set; } public required string PhoneNumber { get; set; } public Guid? DesignId { get; set; } public int Quantity { get; set; } public required string EnquiryType { get; set; } public DateTime? RequiredDate { get; set; } public string? Notes { get; set; } public string? ReferenceImageUrl { get; set; } public string Status { get; set; } = "New"; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public sealed class BulkEnquiry : Entity { public Guid BusinessId { get; set; } public Guid? CustomerId { get; set; } public required string ProductType { get; set; } public required string CustomerName { get; set; } public required string MobileNumber { get; set; } public string? Email { get; set; } public string? CompanyName { get; set; } public int Quantity { get; set; } public string? LogoOrDesignImageUrl { get; set; } public required string EmbroideryPlacement { get; set; } public DateOnly RequiredDate { get; set; } public required string DeliveryPincode { get; set; } public string? AdditionalRequirements { get; set; } public decimal? QuotationAmount { get; set; } public string? InternalNotes { get; set; } public BulkEnquiryStatus Status { get; set; } }
public sealed class Order : Entity { public required string OrderNumber { get; set; } public Guid CustomerId { get; set; } public Guid BusinessId { get; set; } public Guid? ProductId { get; set; } public Guid? BulkEnquiryId { get; set; } public int Quantity { get; set; } public OrderType OrderType { get; set; } public decimal Subtotal { get; set; } public decimal TotalAmount { get; set; } public decimal AdvanceAmount { get; set; } public decimal BalanceAmount { get; set; } public OrderStatus Status { get; set; } public required string DeliveryMethod { get; set; } public string? DeliveryAddress { get; set; } public required string Pincode { get; set; } public DateOnly? ExpectedCompletionDate { get; set; } }
public sealed class OrderStatusHistory : Entity { public Guid OrderId { get; set; } public OrderStatus Status { get; set; } public string? Comment { get; set; } public Guid ChangedByUserId { get; set; } }
