using SundarEmbroidery.Domain;
namespace SundarEmbroidery.Application;
public interface ICatalogService { IReadOnlyList<Category> GetCategories(); IReadOnlyList<Product> GetProducts(Guid? categoryId=null,bool? bulk=null); Product? GetProduct(Guid id); Business GetBusiness(); bool ServicesPincode(string pincode); }
public sealed class DemoCatalogService : ICatalogService
{
 public static readonly Guid SundarBusinessId=Guid.Parse("7c3e58e2-fc40-4d17-b163-06ef1171bb61"); readonly List<Category> categories; readonly List<Product> products;
 public DemoCatalogService(){var names=new[]{"Saree Embroidery","Blouse Embroidery","Bridal Embroidery","T-Shirt Logo Embroidery","Uniform Embroidery","Caps & Bags","Bulk Embroidery"};categories=names.Select(n=>new Category{Name=n,Slug=n.ToLowerInvariant().Replace(" & ","-").Replace(" ","-")}).ToList();var samples=new[]{(0,"Royal Floral Saree Border",false),(1,"Peacock Bridal Blouse",false),(2,"Gold Zari Bridal Pattern",false),(3,"Company Logo Stitching",true),(4,"School Uniform Logo",true),(5,"Custom Cap Embroidery",true),(0,"Temple Motif Pallu",false),(1,"Fine Floral Neckline",false)};products=samples.Select((x,i)=>new Product{BusinessId=SundarBusinessId,CategoryId=categories[x.Item1].Id,Name=x.Item2,Slug=x.Item2.ToLowerInvariant().Replace(" ","-"),ShortDescription="Custom embroidery prepared by our Anantapur workshop.",Description="Contact our team to confirm fabric, thread colours, dimensions, price and production time.",PriceType=PriceType.QuoteOnly,ProductionDaysMin=3,ProductionDaysMax=x.Item3?10:7,MinimumOrderQuantity=x.Item3?10:1,IsBulkAvailable=x.Item3,IsFeatured=i<4}).ToList();}
 public IReadOnlyList<Category> GetCategories()=>categories; public IReadOnlyList<Product> GetProducts(Guid? categoryId=null,bool? bulk=null)=>products.Where(p=>(categoryId is null||p.CategoryId==categoryId)&&(bulk is null||p.IsBulkAvailable==bulk)).ToList(); public Product? GetProduct(Guid id)=>products.FirstOrDefault(p=>p.Id==id); public bool ServicesPincode(string pincode)=>pincode.Length==6&&pincode.All(char.IsDigit);
 public Business GetBusiness()=>new(){Id=SundarBusinessId,OwnerUserId=Guid.Empty,BusinessName="Sundar Embroidery Works",Description="Custom embroidery for sarees, blouses, uniforms, logos, caps and bags.",AddressLine1="Shop No. 7, Raghuveera Towers",Area="Kamala Nagar",City="Anantapur",District="Anantapur",State="Andhra Pradesh",Pincode="515001",WhatsAppNumber="+919849946388",CallingNumber="+919849946388",OpeningTime=new TimeOnly(10,0),ClosingTime=new TimeOnly(21,0),IsActive=true};
}
